### ISSUE TITLE
Invalid returns from comparison operator

### ISSUE THREAD

**Issue by Itay2805** [managarm/lai#102]
According to the ACPI spec in AML True is equals to Ones, but in Lai you return 1 for True instead (for example in `lai_obj_exec_match_op`)

**Comment by thomtl** [comment]
For future reference, ACPI 6.3 19.2.4,
![image](https://user-images.githubusercontent.com/31631330/123822848-edeca800-d8fc-11eb-9072-ff8fe4864d74.png)
