### ISSUE TITLE
Hanging on Intel Core i3-10th gen laptop (Lenovo)

### ISSUE THREAD

**Issue by circutrider21** [managarm/lai#118]
LAI hangs when managarm tries to enable ACPI![image](https://user-images.githubusercontent.com/57774961/163741745-6404466d-e5bf-4935-8902-e8041e2c85a0.jpeg)

**Comment by thomtl** [comment]
Starting with commit d51cd9d052f0a269d0df283ff138f4ec839fe4b8 lai should gracefully ignore this, if this is thesame issue as on 2 other machines with thesame symptom, the proper solution would be to enable the EC, which you can find an example of in the docs.
